server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://@github.com/Yang1998708/microservicecloud-config.git #GitHub上面的git仓库名字
 
management:
  cloudfoundry:
    skip-ssl-validation: true